[2025-04-11T14:53:52.820+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline_modo_prueba.merge_datasets manual__2025-04-11T14:43:29.579813+00:00 [queued]>
[2025-04-11T14:53:52.829+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline_modo_prueba.merge_datasets manual__2025-04-11T14:43:29.579813+00:00 [queued]>
[2025-04-11T14:53:52.830+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-04-11T14:53:52.867+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): merge_datasets> on 2025-04-11 14:43:29.579813+00:00
[2025-04-11T14:53:52.873+0000] {standard_task_runner.py:60} INFO - Started process 182 to run task
[2025-04-11T14:53:52.876+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline_modo_prueba', 'merge_datasets', 'manual__2025-04-11T14:43:29.579813+00:00', '--job-id', '551', '--raw', '--subdir', 'DAGS_FOLDER/etl_workflow.py', '--cfg-path', '/tmp/tmp5w766exm']
[2025-04-11T14:53:52.877+0000] {standard_task_runner.py:88} INFO - Job 551: Subtask merge_datasets
[2025-04-11T14:53:52.954+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_pipeline_modo_prueba.merge_datasets manual__2025-04-11T14:43:29.579813+00:00 [running]> on host a522a5d9503c
[2025-04-11T14:53:53.132+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='simon' AIRFLOW_CTX_DAG_ID='etl_pipeline_modo_prueba' AIRFLOW_CTX_TASK_ID='merge_datasets' AIRFLOW_CTX_EXECUTION_DATE='2025-04-11T14:43:29.579813+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-11T14:43:29.579813+00:00'
[2025-04-11T14:53:53.133+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-11T14:53:53.134+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/scripts/merge_datasets.py']
[2025-04-11T14:53:53.146+0000] {subprocess.py:86} INFO - Output:
[2025-04-11T14:53:54.154+0000] {subprocess.py:93} INFO - üì• Cargando datasets...
[2025-04-11T14:53:54.155+0000] {subprocess.py:93} INFO - ‚úÖ Carga completada.
[2025-04-11T14:53:54.155+0000] {subprocess.py:93} INFO - üìä Agrupando Spotify...
[2025-04-11T14:53:54.155+0000] {subprocess.py:93} INFO - üèÜ Agrupando Grammy...
[2025-04-11T14:53:54.155+0000] {subprocess.py:93} INFO - üìä Agrupando Last.fm...
[2025-04-11T14:53:54.155+0000] {subprocess.py:93} INFO - üîÄ Uniendo Spotify y Grammy...
[2025-04-11T14:53:54.156+0000] {subprocess.py:93} INFO - üìà Uniendo con Last.fm...
[2025-04-11T14:53:54.156+0000] {subprocess.py:93} INFO - üíæ Guardando dataset final...
[2025-04-11T14:53:54.156+0000] {subprocess.py:93} INFO - ‚úÖ Dataset final guardado exitosamente.
[2025-04-11T14:53:54.237+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-11T14:53:54.302+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_pipeline_modo_prueba, task_id=merge_datasets, execution_date=20250411T144329, start_date=20250411T145352, end_date=20250411T145354
[2025-04-11T14:53:54.371+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-11T14:53:54.397+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
