[2025-04-09T07:11:29.523+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline_modo_prueba.load_to_sqlite manual__2025-04-09T07:11:12.014769+00:00 [queued]>
[2025-04-09T07:11:29.535+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline_modo_prueba.load_to_sqlite manual__2025-04-09T07:11:12.014769+00:00 [queued]>
[2025-04-09T07:11:29.535+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-04-09T07:11:29.581+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): load_to_sqlite> on 2025-04-09 07:11:12.014769+00:00
[2025-04-09T07:11:29.589+0000] {standard_task_runner.py:60} INFO - Started process 180 to run task
[2025-04-09T07:11:29.592+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline_modo_prueba', 'load_to_sqlite', 'manual__2025-04-09T07:11:12.014769+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/etl_workflow.py', '--cfg-path', '/tmp/tmp45wa0qx8']
[2025-04-09T07:11:29.595+0000] {standard_task_runner.py:88} INFO - Job 84: Subtask load_to_sqlite
[2025-04-09T07:11:29.708+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_pipeline_modo_prueba.load_to_sqlite manual__2025-04-09T07:11:12.014769+00:00 [running]> on host 6d74a53745cf
[2025-04-09T07:11:29.876+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='simon' AIRFLOW_CTX_DAG_ID='etl_pipeline_modo_prueba' AIRFLOW_CTX_TASK_ID='load_to_sqlite' AIRFLOW_CTX_EXECUTION_DATE='2025-04-09T07:11:12.014769+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-09T07:11:12.014769+00:00'
[2025-04-09T07:11:29.878+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-09T07:11:29.879+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/scripts/load_to_sqlite.py']
[2025-04-09T07:11:29.892+0000] {subprocess.py:86} INFO - Output:
[2025-04-09T07:11:30.391+0000] {subprocess.py:93} INFO - ‚ùå Error al cargar los datos: [Errno 2] No such file or directory: '../data/processed/final_merged.parquet'
[2025-04-09T07:11:30.517+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-09T07:11:30.595+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_pipeline_modo_prueba, task_id=load_to_sqlite, execution_date=20250409T071112, start_date=20250409T071129, end_date=20250409T071130
[2025-04-09T07:11:30.687+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-09T07:11:30.711+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
