[2025-04-09T21:22:48.300+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline_modo_prueba.extract_lastfm manual__2025-04-09T21:12:03.829920+00:00 [queued]>
[2025-04-09T21:22:48.315+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline_modo_prueba.extract_lastfm manual__2025-04-09T21:12:03.829920+00:00 [queued]>
[2025-04-09T21:22:48.316+0000] {taskinstance.py:2170} INFO - Starting attempt 3 of 4
[2025-04-09T21:22:48.371+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): extract_lastfm> on 2025-04-09 21:12:03.829920+00:00
[2025-04-09T21:22:48.378+0000] {standard_task_runner.py:60} INFO - Started process 143 to run task
[2025-04-09T21:22:48.380+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline_modo_prueba', 'extract_lastfm', 'manual__2025-04-09T21:12:03.829920+00:00', '--job-id', '181', '--raw', '--subdir', 'DAGS_FOLDER/etl_workflow.py', '--cfg-path', '/tmp/tmpldfbi3l6']
[2025-04-09T21:22:48.382+0000] {standard_task_runner.py:88} INFO - Job 181: Subtask extract_lastfm
[2025-04-09T21:22:48.485+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_pipeline_modo_prueba.extract_lastfm manual__2025-04-09T21:12:03.829920+00:00 [running]> on host 8bba8f321599
[2025-04-09T21:22:48.632+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='simon' AIRFLOW_CTX_DAG_ID='etl_pipeline_modo_prueba' AIRFLOW_CTX_TASK_ID='extract_lastfm' AIRFLOW_CTX_EXECUTION_DATE='2025-04-09T21:12:03.829920+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-09T21:12:03.829920+00:00'
[2025-04-09T21:22:48.634+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-09T21:22:48.635+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/scripts/extract_lastfm.py']
[2025-04-09T21:22:48.648+0000] {subprocess.py:86} INFO - Output:
[2025-04-09T21:23:08.664+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2025-04-09T21:23:08.666+0000] {process_utils.py:131} INFO - Sending 15 to group 143. PIDs of all processes in the group: [146, 143]
[2025-04-09T21:23:08.667+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 143
[2025-04-09T21:23:08.667+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-04-09T21:23:08.667+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2025-04-09T21:23:08.684+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 203, in execute
    result = self.subprocess_hook.run_command(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2452, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-04-09T21:23:08.689+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_pipeline_modo_prueba, task_id=extract_lastfm, execution_date=20250409T211203, start_date=20250409T212248, end_date=20250409T212308
[2025-04-09T21:23:08.733+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 181 for task extract_lastfm (Task received SIGTERM signal; 143)
[2025-04-09T21:23:08.760+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=146, status='terminated', started='21:22:47') (146) terminated with exit code None
[2025-04-09T21:23:08.761+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=143, status='terminated', exitcode=1, started='21:22:47') (143) terminated with exit code 1
