[2025-04-11T05:56:55.275+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline_modo_prueba.merge_datasets manual__2025-04-11T05:50:45.806125+00:00 [queued]>
[2025-04-11T05:56:55.285+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline_modo_prueba.merge_datasets manual__2025-04-11T05:50:45.806125+00:00 [queued]>
[2025-04-11T05:56:55.285+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-04-11T05:56:55.330+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): merge_datasets> on 2025-04-11 05:50:45.806125+00:00
[2025-04-11T05:56:55.336+0000] {standard_task_runner.py:60} INFO - Started process 179 to run task
[2025-04-11T05:56:55.339+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline_modo_prueba', 'merge_datasets', 'manual__2025-04-11T05:50:45.806125+00:00', '--job-id', '438', '--raw', '--subdir', 'DAGS_FOLDER/etl_workflow.py', '--cfg-path', '/tmp/tmpu0ag9vwa']
[2025-04-11T05:56:55.340+0000] {standard_task_runner.py:88} INFO - Job 438: Subtask merge_datasets
[2025-04-11T05:56:55.418+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_pipeline_modo_prueba.merge_datasets manual__2025-04-11T05:50:45.806125+00:00 [running]> on host bdba95992caa
[2025-04-11T05:56:55.593+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='simon' AIRFLOW_CTX_DAG_ID='etl_pipeline_modo_prueba' AIRFLOW_CTX_TASK_ID='merge_datasets' AIRFLOW_CTX_EXECUTION_DATE='2025-04-11T05:50:45.806125+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-11T05:50:45.806125+00:00'
[2025-04-11T05:56:55.594+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-11T05:56:55.595+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/scripts/merge_datasets.py']
[2025-04-11T05:56:55.607+0000] {subprocess.py:86} INFO - Output:
[2025-04-11T05:56:56.065+0000] {subprocess.py:93} INFO - ❌ Error durante el merge: ❌ No se encontró la columna 'artist' en Spotify.
[2025-04-11T05:56:56.149+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-11T05:56:56.202+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_pipeline_modo_prueba, task_id=merge_datasets, execution_date=20250411T055045, start_date=20250411T055655, end_date=20250411T055656
[2025-04-11T05:56:56.312+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-11T05:56:56.338+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
