[2025-04-11T08:06:55.995+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline_modo_prueba.load_to_sqlite manual__2025-04-11T08:00:42.335962+00:00 [queued]>
[2025-04-11T08:06:56.006+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline_modo_prueba.load_to_sqlite manual__2025-04-11T08:00:42.335962+00:00 [queued]>
[2025-04-11T08:06:56.007+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-04-11T08:06:56.041+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): load_to_sqlite> on 2025-04-11 08:00:42.335962+00:00
[2025-04-11T08:06:56.046+0000] {standard_task_runner.py:60} INFO - Started process 204 to run task
[2025-04-11T08:06:56.050+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline_modo_prueba', 'load_to_sqlite', 'manual__2025-04-11T08:00:42.335962+00:00', '--job-id', '473', '--raw', '--subdir', 'DAGS_FOLDER/etl_workflow.py', '--cfg-path', '/tmp/tmpz20hjj0d']
[2025-04-11T08:06:56.051+0000] {standard_task_runner.py:88} INFO - Job 473: Subtask load_to_sqlite
[2025-04-11T08:06:56.117+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_pipeline_modo_prueba.load_to_sqlite manual__2025-04-11T08:00:42.335962+00:00 [running]> on host bf93b1b59d43
[2025-04-11T08:06:56.296+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='simon' AIRFLOW_CTX_DAG_ID='etl_pipeline_modo_prueba' AIRFLOW_CTX_TASK_ID='load_to_sqlite' AIRFLOW_CTX_EXECUTION_DATE='2025-04-11T08:00:42.335962+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-11T08:00:42.335962+00:00'
[2025-04-11T08:06:56.297+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-11T08:06:56.298+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/scripts/load_to_sqlite.py']
[2025-04-11T08:06:56.311+0000] {subprocess.py:86} INFO - Output:
[2025-04-11T08:06:56.768+0000] {subprocess.py:93} INFO - ‚ùå Error al cargar los datos: [Errno 2] No such file or directory: '/opt/***/data/processed/final_database.parquet'
[2025-04-11T08:06:56.861+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-11T08:06:56.947+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_pipeline_modo_prueba, task_id=load_to_sqlite, execution_date=20250411T080042, start_date=20250411T080655, end_date=20250411T080656
[2025-04-11T08:06:57.023+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-11T08:06:57.046+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
