[2025-04-11T08:18:27.110+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline_modo_prueba.merge_datasets manual__2025-04-11T08:12:16.947734+00:00 [queued]>
[2025-04-11T08:18:27.120+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline_modo_prueba.merge_datasets manual__2025-04-11T08:12:16.947734+00:00 [queued]>
[2025-04-11T08:18:27.120+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-04-11T08:18:27.160+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): merge_datasets> on 2025-04-11 08:12:16.947734+00:00
[2025-04-11T08:18:27.166+0000] {standard_task_runner.py:60} INFO - Started process 179 to run task
[2025-04-11T08:18:27.169+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline_modo_prueba', 'merge_datasets', 'manual__2025-04-11T08:12:16.947734+00:00', '--job-id', '483', '--raw', '--subdir', 'DAGS_FOLDER/etl_workflow.py', '--cfg-path', '/tmp/tmpk16b991_']
[2025-04-11T08:18:27.170+0000] {standard_task_runner.py:88} INFO - Job 483: Subtask merge_datasets
[2025-04-11T08:18:27.276+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_pipeline_modo_prueba.merge_datasets manual__2025-04-11T08:12:16.947734+00:00 [running]> on host b1a5844509db
[2025-04-11T08:18:27.496+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='simon' AIRFLOW_CTX_DAG_ID='etl_pipeline_modo_prueba' AIRFLOW_CTX_TASK_ID='merge_datasets' AIRFLOW_CTX_EXECUTION_DATE='2025-04-11T08:12:16.947734+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-11T08:12:16.947734+00:00'
[2025-04-11T08:18:27.497+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-11T08:18:27.498+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/scripts/merge_datasets.py']
[2025-04-11T08:18:27.512+0000] {subprocess.py:86} INFO - Output:
[2025-04-11T08:18:28.420+0000] {subprocess.py:93} INFO - üì• Cargando datasets...
[2025-04-11T08:18:28.421+0000] {subprocess.py:93} INFO - ‚úÖ Carga completada.
[2025-04-11T08:18:28.421+0000] {subprocess.py:93} INFO - üìä Agrupando Spotify...
[2025-04-11T08:18:28.421+0000] {subprocess.py:93} INFO - üèÜ Agrupando Grammy...
[2025-04-11T08:18:28.422+0000] {subprocess.py:93} INFO - üìä Agrupando Last.fm...
[2025-04-11T08:18:28.422+0000] {subprocess.py:93} INFO - üîÄ Uniendo Spotify y Grammy...
[2025-04-11T08:18:28.422+0000] {subprocess.py:93} INFO - üìà Uniendo con Last.fm...
[2025-04-11T08:18:28.422+0000] {subprocess.py:93} INFO - üíæ Guardando dataset final...
[2025-04-11T08:18:28.422+0000] {subprocess.py:93} INFO - ‚úÖ Dataset final guardado exitosamente.
[2025-04-11T08:18:28.506+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-11T08:18:28.605+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_pipeline_modo_prueba, task_id=merge_datasets, execution_date=20250411T081216, start_date=20250411T081827, end_date=20250411T081828
[2025-04-11T08:18:28.703+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-11T08:18:28.732+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
