[2025-04-11T04:36:53.126+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline_modo_prueba.merge_datasets manual__2025-04-11T04:30:36.796988+00:00 [queued]>
[2025-04-11T04:36:53.136+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline_modo_prueba.merge_datasets manual__2025-04-11T04:30:36.796988+00:00 [queued]>
[2025-04-11T04:36:53.136+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-04-11T04:36:53.173+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): merge_datasets> on 2025-04-11 04:30:36.796988+00:00
[2025-04-11T04:36:53.179+0000] {standard_task_runner.py:60} INFO - Started process 178 to run task
[2025-04-11T04:36:53.183+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline_modo_prueba', 'merge_datasets', 'manual__2025-04-11T04:30:36.796988+00:00', '--job-id', '384', '--raw', '--subdir', 'DAGS_FOLDER/etl_workflow.py', '--cfg-path', '/tmp/tmpahw_poj9']
[2025-04-11T04:36:53.184+0000] {standard_task_runner.py:88} INFO - Job 384: Subtask merge_datasets
[2025-04-11T04:36:53.259+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_pipeline_modo_prueba.merge_datasets manual__2025-04-11T04:30:36.796988+00:00 [running]> on host a96ee05bd6a2
[2025-04-11T04:36:53.419+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='simon' AIRFLOW_CTX_DAG_ID='etl_pipeline_modo_prueba' AIRFLOW_CTX_TASK_ID='merge_datasets' AIRFLOW_CTX_EXECUTION_DATE='2025-04-11T04:30:36.796988+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-11T04:30:36.796988+00:00'
[2025-04-11T04:36:53.420+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-11T04:36:53.421+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/scripts/merge_datasets.py']
[2025-04-11T04:36:53.434+0000] {subprocess.py:86} INFO - Output:
[2025-04-11T04:36:56.851+0000] {subprocess.py:93} INFO - ❌ Error durante el merge: ❌ 'artist' no está en Spotify
[2025-04-11T04:36:56.938+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-11T04:36:57.006+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_pipeline_modo_prueba, task_id=merge_datasets, execution_date=20250411T043036, start_date=20250411T043653, end_date=20250411T043657
[2025-04-11T04:36:57.081+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-11T04:36:57.109+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
