[2025-04-09T06:58:43.320+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline_modo_prueba.merge_datasets manual__2025-04-09T06:58:30.412872+00:00 [queued]>
[2025-04-09T06:58:43.331+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline_modo_prueba.merge_datasets manual__2025-04-09T06:58:30.412872+00:00 [queued]>
[2025-04-09T06:58:43.332+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-04-09T06:58:43.394+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): merge_datasets> on 2025-04-09 06:58:30.412872+00:00
[2025-04-09T06:58:43.402+0000] {standard_task_runner.py:60} INFO - Started process 235 to run task
[2025-04-09T06:58:43.406+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline_modo_prueba', 'merge_datasets', 'manual__2025-04-09T06:58:30.412872+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/etl_workflow.py', '--cfg-path', '/tmp/tmpj8__hstj']
[2025-04-09T06:58:43.408+0000] {standard_task_runner.py:88} INFO - Job 72: Subtask merge_datasets
[2025-04-09T06:58:43.500+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_pipeline_modo_prueba.merge_datasets manual__2025-04-09T06:58:30.412872+00:00 [running]> on host fc23817944d5
[2025-04-09T06:58:43.712+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='simon' AIRFLOW_CTX_DAG_ID='etl_pipeline_modo_prueba' AIRFLOW_CTX_TASK_ID='merge_datasets' AIRFLOW_CTX_EXECUTION_DATE='2025-04-09T06:58:30.412872+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-09T06:58:30.412872+00:00'
[2025-04-09T06:58:43.714+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-09T06:58:43.716+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/scripts/merge_datasets.py']
[2025-04-09T06:58:43.740+0000] {subprocess.py:86} INFO - Output:
[2025-04-09T06:58:44.257+0000] {subprocess.py:93} INFO - ‚ùå Error durante el merge: [Errno 2] No such file or directory: '../data/processed/spotify_transformed.parquet'
[2025-04-09T06:58:44.344+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-09T06:58:44.402+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_pipeline_modo_prueba, task_id=merge_datasets, execution_date=20250409T065830, start_date=20250409T065843, end_date=20250409T065844
[2025-04-09T06:58:44.461+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-09T06:58:44.499+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
