[2025-04-09T18:08:37.450+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline_modo_prueba.extract_lastfm manual__2025-04-09T17:53:58.582038+00:00 [queued]>
[2025-04-09T18:08:37.462+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline_modo_prueba.extract_lastfm manual__2025-04-09T17:53:58.582038+00:00 [queued]>
[2025-04-09T18:08:37.462+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 3
[2025-04-09T18:08:37.509+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): extract_lastfm> on 2025-04-09 17:53:58.582038+00:00
[2025-04-09T18:08:37.516+0000] {standard_task_runner.py:60} INFO - Started process 157 to run task
[2025-04-09T18:08:37.519+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline_modo_prueba', 'extract_lastfm', 'manual__2025-04-09T17:53:58.582038+00:00', '--job-id', '138', '--raw', '--subdir', 'DAGS_FOLDER/etl_workflow.py', '--cfg-path', '/tmp/tmp2_70i1ct']
[2025-04-09T18:08:37.521+0000] {standard_task_runner.py:88} INFO - Job 138: Subtask extract_lastfm
[2025-04-09T18:08:37.610+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_pipeline_modo_prueba.extract_lastfm manual__2025-04-09T17:53:58.582038+00:00 [running]> on host 6493c8ab4351
[2025-04-09T18:08:37.734+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='simon' AIRFLOW_CTX_DAG_ID='etl_pipeline_modo_prueba' AIRFLOW_CTX_TASK_ID='extract_lastfm' AIRFLOW_CTX_EXECUTION_DATE='2025-04-09T17:53:58.582038+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-09T17:53:58.582038+00:00'
[2025-04-09T18:08:37.736+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-09T18:08:37.737+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/scripts/extract_lastfm.py']
[2025-04-09T18:08:37.749+0000] {subprocess.py:86} INFO - Output:
[2025-04-09T18:08:57.840+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2025-04-09T18:08:57.842+0000] {process_utils.py:131} INFO - Sending 15 to group 157. PIDs of all processes in the group: [158, 157]
[2025-04-09T18:08:57.842+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 157
[2025-04-09T18:08:57.842+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-04-09T18:08:57.843+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2025-04-09T18:08:57.857+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 203, in execute
    result = self.subprocess_hook.run_command(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2452, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-04-09T18:08:57.860+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_pipeline_modo_prueba, task_id=extract_lastfm, execution_date=20250409T175358, start_date=20250409T180837, end_date=20250409T180857
[2025-04-09T18:08:57.907+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 138 for task extract_lastfm (Task received SIGTERM signal; 157)
[2025-04-09T18:08:57.935+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=158, status='terminated', started='18:08:37') (158) terminated with exit code None
[2025-04-09T18:08:57.936+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=157, status='terminated', exitcode=1, started='18:08:37') (157) terminated with exit code 1
