[2025-04-09T07:28:13.682+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline_modo_prueba.merge_datasets manual__2025-04-09T07:27:59.723185+00:00 [queued]>
[2025-04-09T07:28:13.699+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline_modo_prueba.merge_datasets manual__2025-04-09T07:27:59.723185+00:00 [queued]>
[2025-04-09T07:28:13.700+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-04-09T07:28:13.743+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): merge_datasets> on 2025-04-09 07:27:59.723185+00:00
[2025-04-09T07:28:13.749+0000] {standard_task_runner.py:60} INFO - Started process 124 to run task
[2025-04-09T07:28:13.752+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline_modo_prueba', 'merge_datasets', 'manual__2025-04-09T07:27:59.723185+00:00', '--job-id', '94', '--raw', '--subdir', 'DAGS_FOLDER/etl_workflow.py', '--cfg-path', '/tmp/tmpltma9jse']
[2025-04-09T07:28:13.753+0000] {standard_task_runner.py:88} INFO - Job 94: Subtask merge_datasets
[2025-04-09T07:28:13.834+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_pipeline_modo_prueba.merge_datasets manual__2025-04-09T07:27:59.723185+00:00 [running]> on host d9666b3d8245
[2025-04-09T07:28:13.987+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='simon' AIRFLOW_CTX_DAG_ID='etl_pipeline_modo_prueba' AIRFLOW_CTX_TASK_ID='merge_datasets' AIRFLOW_CTX_EXECUTION_DATE='2025-04-09T07:27:59.723185+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-09T07:27:59.723185+00:00'
[2025-04-09T07:28:13.989+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-09T07:28:13.990+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/scripts/merge_datasets.py']
[2025-04-09T07:28:14.003+0000] {subprocess.py:86} INFO - Output:
[2025-04-09T07:28:14.530+0000] {subprocess.py:93} INFO - ‚ùå Error durante el merge: [Errno 2] No such file or directory: '../data/processed/spotify_transformed.parquet'
[2025-04-09T07:28:14.642+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-09T07:28:14.694+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_pipeline_modo_prueba, task_id=merge_datasets, execution_date=20250409T072759, start_date=20250409T072813, end_date=20250409T072814
[2025-04-09T07:28:14.767+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-09T07:28:14.795+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
