[2025-04-11T07:55:16.033+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline_modo_prueba.merge_datasets manual__2025-04-11T07:49:05.654264+00:00 [queued]>
[2025-04-11T07:55:16.043+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline_modo_prueba.merge_datasets manual__2025-04-11T07:49:05.654264+00:00 [queued]>
[2025-04-11T07:55:16.043+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-04-11T07:55:16.089+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): merge_datasets> on 2025-04-11 07:49:05.654264+00:00
[2025-04-11T07:55:16.095+0000] {standard_task_runner.py:60} INFO - Started process 176 to run task
[2025-04-11T07:55:16.098+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline_modo_prueba', 'merge_datasets', 'manual__2025-04-11T07:49:05.654264+00:00', '--job-id', '461', '--raw', '--subdir', 'DAGS_FOLDER/etl_workflow.py', '--cfg-path', '/tmp/tmpf40rc9m4']
[2025-04-11T07:55:16.100+0000] {standard_task_runner.py:88} INFO - Job 461: Subtask merge_datasets
[2025-04-11T07:55:16.210+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_pipeline_modo_prueba.merge_datasets manual__2025-04-11T07:49:05.654264+00:00 [running]> on host 6c0b66bf1576
[2025-04-11T07:55:16.404+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='simon' AIRFLOW_CTX_DAG_ID='etl_pipeline_modo_prueba' AIRFLOW_CTX_TASK_ID='merge_datasets' AIRFLOW_CTX_EXECUTION_DATE='2025-04-11T07:49:05.654264+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-11T07:49:05.654264+00:00'
[2025-04-11T07:55:16.406+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-11T07:55:16.407+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/scripts/merge_datasets.py']
[2025-04-11T07:55:16.420+0000] {subprocess.py:86} INFO - Output:
[2025-04-11T07:55:17.328+0000] {subprocess.py:93} INFO - üì• Cargando datasets...
[2025-04-11T07:55:17.328+0000] {subprocess.py:93} INFO - ‚úÖ Carga completada.
[2025-04-11T07:55:17.328+0000] {subprocess.py:93} INFO - üìä Agrupando Spotify...
[2025-04-11T07:55:17.329+0000] {subprocess.py:93} INFO - üèÜ Agrupando Grammy...
[2025-04-11T07:55:17.329+0000] {subprocess.py:93} INFO - üìä Agrupando Last.fm...
[2025-04-11T07:55:17.329+0000] {subprocess.py:93} INFO - üîÄ Uniendo Spotify y Grammy...
[2025-04-11T07:55:17.329+0000] {subprocess.py:93} INFO - üìà Uniendo con Last.fm...
[2025-04-11T07:55:17.329+0000] {subprocess.py:93} INFO - üíæ Guardando dataset final...
[2025-04-11T07:55:17.329+0000] {subprocess.py:93} INFO - ‚úÖ Dataset final guardado exitosamente.
[2025-04-11T07:55:17.418+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-11T07:55:17.482+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_pipeline_modo_prueba, task_id=merge_datasets, execution_date=20250411T074905, start_date=20250411T075516, end_date=20250411T075517
[2025-04-11T07:55:17.553+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-11T07:55:17.581+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
